workspace = { members = ["crates/core", "crates/ui"] }

[package]
name = "synk"
version = "0.1.0"
edition = "2021"

[features]
wayland = []
x11 = []

[dependencies]
ui = { path = "crates/ui" }
core = { path = "crates/core" }
anyhow = "1.0.79"
xilem = { git = "https://github.com/linebender/xilem" }
