[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.25.0", default-features = false, features = [
	"glow",
	"default_fonts",
	"wayland",
] }
anyhow = "1.0.79"
egui = "0.25.0"
