[package]
name = "synk-core"
version = "0.1.0"
edition = "2021"


[dependencies]
iced = { version = "0.10", features = ["lazy", "debug"] }
iced_aw = { version = "*", git = "https://github.com/synkdev/iced_aw/", features = [
    "split",
] }
