[package]
name = "synk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "synk"
path = "src/main.rs"

[dependencies]
synk-gui = { path = "../synk-gui" }
synk-core = { path = "../synk-core" }
iced = { version = "0.10.0", features = ["image"] }
